### ISSUE TITLE
"SpringBoneWindowのアイコンディレクトリーが見つかりません" の警告が大量に出力される

### ISSUE THREAD

**Issue by zabaglione** [unity3d-jp/UnityChanSpringBone#5]
Unity ProjectのPackages/manifest.jsonに

"com.unity.springbone": "https://github.com/unity3d-jp/UnityChanSpringBone.git#release/1.1",

を追加して利用しようとすると、

SpringBoneWindowのアイコンディレクトリーが見つかりません
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
Unity.Animations.SpringBones.SpringBoneWindow:InitializeIcons() (at Library\PackageCache\com.unity.springbone@8db0f7243b\Editor\GUI\Windows\SpringBoneWindow.cs:61)
Unity.Animations.SpringBones.SpringBoneWindow:OnGUI() (at Library\PackageCache\com.unity.springbone@8db0f7243b\Editor\GUI\Windows\SpringBoneWindow.cs:150)
System.Reflection.MonoMethod:InternalInvoke(Object, Object[], Exception&)
System.Reflection.MonoMethod:Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
System.Reflection.MethodBase:Invoke(Object, Object[])
UnityEditor.HostView:Invoke(String, Object)
UnityEditor.HostView:Invoke(String)
UnityEditor.HostView:InvokeOnGUI(Rect, Rect)
UnityEditor.DockArea:DrawView(Rect, Rect)
UnityEditor.DockArea:OldOnGUI()
UnityEngine.UIElements.IMGUIContainer:DoOnGUI(Event, Matrix4x4, Rect, Boolean, Rect, Action, Boolean)
UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent(Event, Matrix4x4, Rect, Action, Boolean)
UnityEngine.UIElements.IMGUIContainer:DoIMGUIRepaint()
UnityEngine.UIElements.UIR.RenderChainCommand:ExecuteNonDrawMesh(DrawParams, Boolean, Single, Exception&)
UnityEngine.UIElements.UIR.UIRenderDevice:EvaluateChain(RenderChainCommand, Rect, Matrix4x4, PanelClearFlags, Texture, Texture, Texture, Single, NativeArray`1, NativeArray`1, Exception&)
UnityEngine.UIElements.UIR.UIRenderDevice:DrawChain(RenderChainCommand, Rect, Matrix4x4, PanelClearFlags, Texture, Texture, Texture, Single, NativeArray`1, NativeArray`1, Exception&)
UnityEngine.UIElements.UIR.RenderChain:Render(Rect, Matrix4x4, PanelClearFlags)
UnityEngine.UIElements.UIRRepaintUpdater:DrawChain(Rect, Matrix4x4)
UnityEngine.UIElements.UIRRepaintUpdater:Update()
UnityEngine.UIElements.VisualTreeUpdater:UpdateVisualTreePhase(VisualTreeUpdatePhase)
UnityEngine.UIElements.Panel:UpdateForRepaint()
UnityEngine.UIElements.Panel:Repaint(Event)
UnityEngine.UIElements.UIElementsUtility:DoDispatch(BaseVisualElementPanel)
UnityEngine.UIElements.UIElementsUtility:ProcessEvent(Int32, IntPtr)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
 
(Filename: Library/PackageCache/com.unity.springbone@8db0f7243b/Editor/GUI/Windows/SpringBoneWindow.cs Line: 61)

が大量に出力されます。

**Comment by H3idi-X** [comment]
長らくお待たせして、申し訳ございません。release 1.2以降でこの部分のロジックを根本的に変えており、この問題は発生しないはずです。お手数をおかけしますが、1.2以降をお試しいただけますようお願いいたします。

**Comment by zabaglione** [comment]
修正ありがとうございます。1.2を指定することでエラーもなく利用できることを確認しました。
